"""
Import test variants from CSV manifests generated by PDF worker.

Usage:
    python -c "from src.db.test_variant_importer import import_test_variants; import_test_variants()"
"""

import csv
import json
from pathlib import Path
from typing import Optional

from psycopg2.extras import execute_values

from config import db, sql


# Mapping test_id to subject table and variant metadata
TEST_CONFIG = {
    "1-test": {
        "subject": "literature",
        "subject_name": "Ona tili",
        "variant_id": 1,
        "varyant": "1",
        "description": "Test 1 - Ona tili (Majburiy fanlar)"
    },
    "2-test": {
        "subject": "math",
        "subject_name": "Matematika",
        "variant_id": 2,
        "varyant": "2",
        "description": "Test 2 - Matematika (Majburiy fanlar)"
    },
    "3-test": {
        "subject": "history",
        "subject_name": "O'zbekiston tarixi",
        "variant_id": 3,
        "varyant": "3",
        "description": "Test 3 - O'zbekiston tarixi (Majburiy fanlar)"
    }
}


def load_manifest(manifest_path: Path) -> list[dict]:
    """Load question data from CSV manifest."""
    records = []
    with manifest_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            records.append(row)
    return records


def _normalize_photo_path(photo_path: str, project_root: Path, base_image_dir: Optional[Path]) -> str:
    """Store a project-relative path so the server can resolve it after pull."""
    if not photo_path:
        return ""

    candidate = Path(photo_path)
    if candidate.is_absolute():
        try:
            return str(candidate.relative_to(project_root))
        except ValueError:
            if base_image_dir is not None:
                try:
                    return str(candidate.relative_to(base_image_dir.parent))
                except ValueError:
                    pass
            return candidate.name

    return str(candidate)


def import_test_variant(
    test_id: str,
    manifest_path: Path,
    base_image_dir: Optional[Path] = None
) -> tuple[bool, str, int]:
    """
    Import a single test variant from manifest.

    Args:
        test_id: Test identifier (1-test, 2-test, 3-test)
        manifest_path: Path to manifest.csv
        base_image_dir: Optional base directory for image paths (default: manifest parent)

    Returns:
        (success: bool, message: str, rows_imported: int)
    """
    if test_id not in TEST_CONFIG:
        return False, f"Unknown test_id: {test_id}", 0

    if not manifest_path.exists():
        return False, f"Manifest not found: {manifest_path}", 0

    cfg = TEST_CONFIG[test_id]
    table_name = cfg["subject"]
    variant_id = cfg["variant_id"]
    varyant_value = cfg["varyant"]
    project_root = Path(__file__).resolve().parents[2]

    try:
        records = load_manifest(manifest_path)
        if not records:
            return False, f"No records in {manifest_path}", 0

        # Prepare rows for insertion
        rows = []
        for rec in records:
            q_no = int(rec.get("question_no", 0))
            answer = rec.get("answer", "").upper()
            image_path = rec.get("image_path", "")
            photo_value = _normalize_photo_path(image_path, project_root, base_image_dir)

            rows.append((varyant_value, answer, "", "True", photo_value, variant_id, q_no))

        # Insert into database
        sql.execute(
            f"DELETE FROM public.{table_name} WHERE varyant = %s",
            (varyant_value,),
        )
        execute_values(
            sql,
            f"""
            INSERT INTO public.{table_name} (varyant, answer, file_id, status, photo, test_variant_id, question_number)
            VALUES %s
            """,
            rows,
            page_size=100,
        )
        db.commit()

        return True, f"Imported {len(rows)} questions for {test_id}", len(rows)

    except Exception as exc:
        return False, f"Import failed: {exc}", 0


def import_all_test_variants(
    worker_base_dir: Optional[Path] = None
) -> dict:
    """
    Import all test variants from worker output.

    Args:
        worker_base_dir: Root of test_pdf_worker_base (default: auto-detect)

    Returns:
        Dictionary with results for each test
    """
    if worker_base_dir is None:
        worker_base_dir = Path(__file__).resolve().parents[2] / "test_pdf_worker_base"

    if not worker_base_dir.exists():
        return {
            "success": False,
            "error": f"Worker base directory not found: {worker_base_dir}"
        }

    results = {}
    for test_id in TEST_CONFIG.keys():
        manifest_path = worker_base_dir / "output_images" / test_id / "manifest.csv"
        success, msg, count = import_test_variant(
            test_id,
            manifest_path,
            base_image_dir=worker_base_dir / "output_images" / test_id / "question_blocks"
        )
        results[test_id] = {
            "success": success,
            "message": msg,
            "rows_imported": count
        }

    return results


def get_test_variant_questions(
    subject: str,
    variant_id: int,
    question_no: Optional[int] = None
) -> list[dict]:
    """
    Retrieve questions from a test variant.

    Args:
        subject: Subject name (math, literature, history)
        variant_id: Test variant ID (1, 2, 3, ...)
        question_no: Specific question number (optional)

    Returns:
        List of question dictionaries
    """
    if subject not in ("math", "literature", "history"):
        return []

    cur = sql.cursor()
    if question_no is not None:
        cur.execute(
            f"""
            SELECT id, varyant, answer, photo, question_number
            FROM public.{subject}
            WHERE test_variant_id = %s AND question_number = %s
            """,
            (variant_id, question_no)
        )
    else:
        cur.execute(
            f"""
            SELECT id, varyant, answer, photo, question_number
            FROM public.{subject}
            WHERE test_variant_id = %s
            ORDER BY question_number ASC
            """,
            (variant_id,)
        )

    cols = [desc[0] for desc in cur.description]
    rows = cur.fetchall()
    return [dict(zip(cols, row)) for row in rows]


if __name__ == "__main__":
    print("Importing all test variants from worker output...")
    results = import_all_test_variants()
    print(json.dumps(results, indent=2, ensure_ascii=False))
